name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build OpenAPI JSON
        run: npm run build:openapi

      - name: Upload OpenAPI artifact (main, 30d)
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main') }}
        uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          path: backend/openapi.json
          if-no-files-found: error
          retention-days: 30

      - name: Upload OpenAPI artifact (non-main, 7d)
        if: ${{ !((github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main')) }}
        uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          path: backend/openapi.json
          if-no-files-found: error
          retention-days: 7


